[doctor]
checks = [
  { check = "homebrew" },
  { check = "asdf", command = "plugin-installed", args = { plugin = "erlang" } },
  { check = "asdf", command = "plugin-installed", args = { plugin = "elixir" } },
  { check = "asdf", command = "package-installed", args = { plugin = "erlang" } },
  { check = "asdf", command = "package-installed", args = { plugin = "elixir" } },
]

[audit]
checks = [
  { name = "Check formatting", shell = "mix format --check-formatted" },
]

[update]
steps = [
  { step = "git", command = "pull" },
  { doctor = {} },
]

[test]
checks = []

[shipit]
steps = [
  { audit = {} },
  { update = {} },
  { test = {} },
  { name = "Release", shell = "bin/dev/release", verbose = true },
  { step = "git", command = "push" },
  { step = "github", command = "link-to-actions", verbose = true },
]

